### ISSUE TITLE
develop build broken

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene#561]
Is the develop branch build broken?  I have completed a full `make` on a fresh checkout.  This is what I am consistently seeing:

``` c++
/home/jcalfee/graphene/programs/js_operation_serializer/main.cpp:395:39:   required from here
/home/jcalfee/graphene/libraries/fc/include/fc/static_variant.hpp:185:49: error: size of array is not an integral constant-expression
     char storage[impl::type_info<Types...>::size];
                                                 ^
```

**Comment by theoreticalbts** [comment]
It might be, I don't regularly build `js_operation_serializer`.  I'll look into it.   EDIT:  Yep, it's broke.  Looks like maybe a header issue.

**Comment by theoreticalbts** [comment]
Probably broken by #466 .  Try adding to `js_operation_serializer`

```
#include <graphene/chain/confidential_object.hpp>
#include <graphene/chain/market_object.hpp>
#include <graphene/chain/worker_object.hpp>
```

with the other `#include` statements.

**Comment by theoreticalbts** [comment]
We shouldn't actually need these at all, because `asset_id_type` is seralized but `asset_object` is not.  However, it seems somewhere in the guts of `static_variant` implementation it's barfing because the definition of `asset_id_type` is templated with `asset_object` as a template parameter and it doesn't know what to do if `asset_object` is an incomplete type.

**Comment by theoreticalbts** [comment]
Should be fixed now.
